version: 2
updates:
  # Enable version updates for npm (client dependencies)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "patominer"
    assignees:
      - "patominer"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (server dependencies)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "patominer"
    assignees:
      - "patominer"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
    ignore:
      # Ignore major version updates for critical server dependencies
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "stripe"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (root dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "patominer"
    assignees:
      - "patominer"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "root"
    ignore:
      # Ignore major version updates for build tools
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "patominer"
    assignees:
      - "patominer"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "patominer"
    assignees:
      - "patominer"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    labels:
      - "dependencies"
      - "docker"
